version: '3'
services:
  api:
    image: "saibotma/chat-server:0.2.1"
    # The env file is just used for running the production environment on on a local development system
    env_file:
      - .env
    environment:
      - SERVER_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_SERVERNAME
      - POSTGRES_PORT
      - POSTGRES_DB
      - PLATFORM_API_ACCESS_TOKEN
      - CLIENT_API_JWT_SECRET
      - FIREBASE_CREDENTIALS
      - FLYWAY_BASELINE
      - FLYWAY_SHOULD_BASELINE
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
